### ISSUE TITLE
[Bug] This gem can't work with Puma 4.x

### ISSUE THREAD

**Issue by KhanhVanCong** [apicraft-dev/apicraft-rails#6]
Hi team,

Thank you for your effort to create this awesome gem.
I'm trying to use it in my project, but I'm facing an issue. 
## Issue
After I set up and sent a request via Postman, I received a response `500 Internal Server Error` with an empty message. Here is the log I found on my server
```plaintext
#<TypeError: no implicit conversion of Symbol into String>
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/server.rb:807:in `append'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/server.rb:807:in `block (2 levels) in handle_request'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/server.rb:805:in `each'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/server.rb:805:in `block in handle_request'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.10/lib/rack/utils.rb:465:in `block in each'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.10/lib/rack/utils.rb:464:in `each'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.10/lib/rack/utils.rb:464:in `each'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/server.rb:790:in `handle_request'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/server.rb:472:in `process_client'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/server.rb:328:in `block in run'
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/puma-4.3.6/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```
## Version
My project is using:
- Ruby: 3.0.0
- Rails: 6.0.5.1
- puma: 4.3.6

## Analysis
- As I checked, The problem comes from the syntax { `'Content-Type': content_type` } it will return `{:"Content-Type"=>"application/json"}` in file `mocker.rb:33`, the `Content-Type` will be converted as a **Symbol** instead of **String**. It leads the function in `puma-4.3.6/lib/puma/server.rb:807` to raise this error.
It may also affect file `introspector.rb` and `request_validator.rb`.

I hope your team can find a way to solve this issue. Thank you so much.

**Comment by KhanhVanCong** [comment]
I work around and luckily, I found a way to fix it.
I created a file: `header_string_transformer.rb` and put it in `lib/middleware`
```ruby
class HeaderStringTransformer
  def initialize(app)
    @app = app
  end

  def call(env)
    status, headers, body = @app.call(env)
    [status, headers.transform_keys(&:to_s), body]
  end
end

```
After that, In `application.rb`, I set it up like this.

```ruby
require './lib/middleware/header_string_transformer'
.... your_code ...
[
  HeaderStringTransformer,
  Apicraft::Middlewares::Mocker,
  Apicraft::Middlewares::Introspector,
  Apicraft::Middlewares::RequestValidator
].each { |mw| config.middleware.use mw }
```

Restart the server and re-check. I hope it can help someone else

**Comment by KhanhVanCong** [comment]
Hi @KhanhVanCong ,

I updated the latest version `1.0.1` and it works well. Thank you so much.
